name: 'Archive exists'
description: 'Provide a description here'
author: 'fddayan'
inputs:
  artifactName:
    required: true
    description: 'The artifact name to check. It could be a regex expression.'
runs:
  using: 'node12'
  main: 'dist/index.js'
