name: 'Archive exists'
description: 'Provide a description here'
author: 'fddayan'
branding:
  icon: 'alert-triangle'  
  color: 'green'
inputs:
  artifactName:
    required: true
    description: 'The artifact name to check. It could be a regex expression.'
  GITHUB_TOKEN:
    description: 'The GitHub access token (e.g. secrets.GITHUB_TOKEN) used to create or update the comment. This defaults to {{ github.token }}.'
    default: '${{ github.token }}'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
